#+TITLE: 0poss's nix config
#+AUTHOR: 0poss

* NixOS Flake Configuration
This is my full NixOS configuration.

* Notable Features
- [X] Secure Boot
- [X] us-intl in sway
- [ ] Screenshare
- [ ] Fn keys:
  - [X] Volume
  - [X] Brightness
  - [ ] Media keys
- [ ] CCache
- [ ] Easily deployable VMs, most notably for running untrused binaries
- Emacs:
  - [ ] Auto-suggest words in text-mode based on dictonary and other words in the documents.
  - [ ] Increase undo buffer.
  - [ ] Eglot:
    - [ ] Change config s.t. when pressing RET on a function suggestion, the arguments are also inserting, not only the function's name, in function definitions.
- Zsh:
  - [ ] Fuzzy ~C-r~.

* Coding Convention
- Format everything with [[https://github.com/nix-community/nixpkgs-fmt][nixpkgs-fmt]].
- No relative ~imports~ to upper directories. Instead, if a module needs to be accessed from elsewhere in the flake, create or add a reference to it in the ~default.nix~ file inside the parent directory. It can then be imported using ~homeConfFiles~ or ~nixosConfFiles~.
  + Pros :
    * Relative imports are dirty and can be hard to understand for an unfamiliar reader. Referencing imports from the root of the flake puts forward the full logical path of the imported module.
  + Cons :
    * Adding modules to ~default.nix~ files can be cumbersome.
    * More generally, it usually takes more characters and lines just to import modules.
  + Note :
    * You need to be careful not to ~import~ leaf modules (files actually containing a module, not importing a path), otherwise they'll be evaluated as many times as they are imported with ~imports = [ ... ]~ which WILL cause conflicts in ~options~ declarations and definitions.
  + Example :

    Don't do :
    #+begin_src nix
      # home-manager/users/oposs/default.nix
      {
        imports = [ ../base ];
      }
    #+end_src
    Do :
    #+begin_src nix
      # home-manager/users/oposs/default.nix
      { homeConfFiles, ... }:
      {
        imports = with homeConfFiles; [ users.base ];
      }
    #+end_src
    #+begin_src nix
      # home-manager/users/default.nix
      {
        base = ./base;
      }
    #+end_src
    #+begin_src nix
      # home-manager/default.nix
      {
        users = import ./users;
      }
    #+end_src

* Credits
Thanks [[https://github.com/Misterio77][Misterio77]] for his nice [[https://github.com/Misterio77/nix-config][config]].
