#+TITLE: 0poss's nix config
#+AUTHOR: 0poss

* NixOS flake configuration
This is my full NixOS configuration.

* TODO Stuff to do
- Secure boot
- Find a way to secure the local configuration.
  Normal users should be able to modify their home-manager configuration, without being able to backdoor the system (i.e. modifying the NixOS configuration).
- Probably some cleanup. Some stuff aren't where they should be.
- Create a VM configuration for CTFs.

* Coding convention
There's not much :
- I format everything with [[https://github.com/nix-community/nixpkgs-fmt][nixpkgs-fmt]].


- No relative ~imports~ to upper directories. Instead, if a module needs to be accessed from elsewhere in the flake, create or add a reference to it in the ~default.nix~ file inside the parent directory. It can then be imported using ~homeConfFiles~ or ~nixosConfFiles~.
  + Pros :
    * Relative imports are dirty and can be hard to understand for an unfamiliar reader. Referencing imports from the root of the flake puts forward the full logical path of the imported module.
  + Cons :
    * Adding modules to ~default.nix~ files can be cumbersome.
    * More generally, it usually takes more characters and lines just to import modules.
  + Example :

    Don't do :
     #+begin_src nix
  # home-manager/users/oposs/default.nix
  {
    imports = [ ../base ];
  }
#+end_src
    Do :
     #+begin_src nix
  # home-manager/users/oposs/default.nix
  { homeConfFiles, ... }:
  {
    imports = with homeConfFiles; [ users.base ];
  }
#+end_src
    #+begin_src nix
  # home-manager/users/default.nix
  {
    base = import ./base;
  }
#+end_src

* Credits
Thanks [[https://github.com/Misterio77][Misterio77]] for his nice [[https://github.com/Misterio77/nix-config][config]].
